steps:
  - name: hello
    image: alpine
    when:
      event: [push, pull_request]
    environment:
      API_KEY:
        from_secret: PROD_API_KEY
      PRIVATE_KEY:
        from_secret: PROD_PRIVATE_KEY
    commands:
      - echo " Woodpecker CI is running!"
      - echo "API_KEY = '$API_KEY'"
      - echo "PRIVATE_KEY = '$PRIVATE_KEY'"
