steps:
  - name: hello
    image: alpine
    when:
      event: [push, pull_request]
    environment:
      API_KEY:
        from_secret: PROD_API_KEY
      PRIVATE_KEY:
        from_secret: PROD_PRIVATE_KEY
    commands:
      - chmod +x ./deploy.sh
      - ./deploy.sh $API_KEY $PRIVATE_KEY
