steps:
  - name: hello
    image: alpine
    envirnment: 
    API_KEY:
    from_secret: PROD_API_KEY
    commands:
      - echo "✅ Woodpecker CI is running!"
      - echo "API_KEY = $API_KEY"
      - uname -a
      - echo "Pipeline completed successfully."
