steps:
  - name: deploy
    image: alpine
    environment:
      API_KEY:
        from_secret: PROD_API_KEY
      PRIVATE_KEY:
        from_secret: PROD_PRIVATE_KEY
    commands:
      - apk add --no-cache bash curl
      - chmod +x ./deploy.sh
      - ./deploy.sh "$API_KEY" "$PRIVATE_KEY"
