steps:
  - name: hello
    image: alpine
    when:
      event: [push, pull_request]
    environment:
      API_KEY:
        from_secret: PROD_API_KEY
      PRIVATE_KEY:
        from_secret: PROD_PRIVATE_KEY
    commands:
      - echo "Running deploy script..."
      - ls -alt
      - apk add --no-cache bash
      - chmod +x ./deploy.sh     # make script executable
      - ls -alt
      - ./deploy.sh "$API_KEY" "$PRIVATE_KEY"
